import AppKit
import Carbon.HIToolbox
import Foundation
import Sauce

/// Tier 2: pasteboard + synthesized ⌘V — the universal method.
///
/// Hardening (research: every shipping app's bug list):
///  - Snapshot ALL pasteboard item types and restore only if our write is still
///    current (changeCount + session-UUID marker type) — a user copy mid-flight wins.
///  - Transient/AutoGenerated marker types so clipboard managers skip the write.
///  - Layout-correct 'V' keycode via Sauce ('v' is 9 on QWERTY, 47 on Dvorak).
///  - Synthetic events tagged with SyntheticEventTag so our own tap ignores them.
///  - Restore delay ~1s (critic reconciliation #4) — slow apps read the pasteboard
///    late; a too-early restore pastes the user's OLD clipboard.
@MainActor
public final class PasteInserter {
    public static let restoreDelay: TimeInterval = 1.0
    private static let sessionMarker = NSPasteboard.PasteboardType("com.google.transcribe.transient")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public init() {}

    /// Returns true if the ⌘V events were POSTED. There is no OS-level receipt
    /// that the frontmost app performed the paste (audit #12) — this is the
    /// industry floor; the transcript always remains recoverable from History
    /// and stays on the clipboard until restore.
    public func paste(_ text: String) async -> Bool {
        let pasteboard = NSPasteboard.general
        let snapshot = Self.snapshot(pasteboard)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString(UUID().uuidString, forType: Self.sessionMarker)
        item.setString("", forType: Self.transientType)
        item.setString("", forType: Self.autoGeneratedType)
        pasteboard.writeObjects([item])
        let ourChangeCount = pasteboard.changeCount

        // Let the pasteboard write settle before the app reads it.
        try? await Task.sleep(nanoseconds: 100_000_000)

        guard Self.postCmdV() else {
            // Leave the text on the clipboard — it's the fallback content.
            return false
        }

        try? await Task.sleep(nanoseconds: UInt64(Self.restoreDelay * 1_000_000_000))

        // Restore only if nothing else touched the pasteboard since our write.
        if pasteboard.changeCount == ourChangeCount,
           pasteboard.pasteboardItems?.first?.string(forType: Self.sessionMarker) != nil {
            Self.restore(snapshot, to: pasteboard)
        }
        return true
    }

    /// Puts text on the clipboard WITHOUT restore — the tier-3 floor and the
    /// focus-changed path ("Copied — press ⌘V"). Marked transient so clipboard
    /// managers don't archive transcripts (audit L22).
    public func copyOnly(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: Self.transientType)
        pasteboard.writeObjects([item])
    }

    // MARK: - Plumbing

    private static func postCmdV() -> Bool {
        guard let source = CGEventSource(stateID: .privateState) else { return false }
        let keyCode = CGKeyCode(Sauce.shared.keyCode(for: .v))
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) else {
            return false
        }
        for event in [down, up] {
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: SyntheticEventTag.magic)
        }
        down.post(tap: .cghidEventTap)
        usleep(10_000)
        up.post(tap: .cghidEventTap)
        return true
    }

    private static func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? [])
            // Never chain-snapshot our own transient transcript from a previous
            // rapid-fire dictation whose restore hasn't run yet (audit L23).
            .filter { $0.string(forType: sessionMarker) == nil }
            .map { item in
                var entry: [NSPasteboard.PasteboardType: Data] = [:]
                for type in item.types {
                    if let data = item.data(forType: type) {
                        entry[type] = data
                    }
                }
                return entry
            }
    }

    private static func restore(_ snapshot: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }
        let items = snapshot.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(items)
    }
}
